name: verifplus
description: Flutter project.

publish_to: 'none'
version: 1.1.181+181

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_app_badger: ^1.4.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  package_info_plus: ^4.0.2
  maps_launcher: ^2.2.0
  flutter_spinkit: ^5.1.0

  crop_image: ^1.0.12
  getwidget: ^ 2.0.4

  sqflite: ^2.0.2+1
  intl: ^0.19.0
  path: ^1.8.0
  http: ^1.0.0
  uuid: ^4.1.0

  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  firebase_messaging_platform_interface: ^4.2.4
  cloud_firestore_platform_interface: ^5.9.1

  syncfusion_flutter_pdfviewer: ^24.1.46
  syncfusion_flutter_datagrid: ^24.1.46
  smooth_page_indicator: ^1.0.0+2
  flutter_grid_button: ^2.0.0
  dropdown_button2: ^2.0.0

  image_picker: ^0.8.5+3
  image: ^4.0.02
  mailto: ^2.0.0

  open_file: ^3.2.1
  image_painter: ^0.7.1
  csv: ^5.0.1
  toggle_switch: ^2.0.1

  cart_stepper:
  barcode_scan2: ^4.2.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^4.0.0
  davi: ^3.4.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_typeahead: ^5.2.0
  rflutter_alert: ^2.0.7
  sticky_and_expandable_list: ^1.1.3
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.1
  connectivity_plus: ^5.0.2
  wifi_iot: ^0.3.19
  fbroadcast: ^2.0.0
  hand_signature: ^3.0.2

#  camera_android_camerax: ^0.6.7+2
  camera: ^0.11.0+2

  group_button: ^5.3.4
  carousel_slider: ^4.2.1
  time_machine: ^0.9.17

  flutter_svg: ^2.0.14
  quill_html_editor: ^2.2.8

  flutter_html: ^3.0.0-beta.2




dependency_overrides:

  camera_android_camerax: 0.6.7
  camera: 0.11.0


  pdf:
    path: ./pdf
  printing:
    path: ./printing
  month_year_picker:
    path: ./month_year_picker
  marquee:
    path: ./marquee

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf
    - assets/fonts/Arial-Regular.ttf
    - assets/fonts/Arial-Bold.ttf
    - assets/fonts/Arial-Italic.ttf
    - assets/fonts/Arial-BoldItalic.ttf

